### ISSUE TITLE
2016-06-26a "Elenor of Tsort" won't work with Windows 10 Home Edition

### ISSUE THREAD

**Issue by deeplunacy** [splitbrain/dokuwiki-stickbuilder#1]
Please supply the latest version of php5ts.dll (namely 5.6.26) with your release of Microapache. If I use previous version of this DLL (included with your release) the server crashes and then restarts in infinite loop on Windows 10 Home edition.

**Comment by bytecrook** [comment]
I found the same issue with as deeplunacy. Downloading the 2016-Sep-16 version of php5ts.dll from http://windows.php.net/download/ solves this issue.

**Comment by splitbrain** [comment]
I updated the download. Can you please try again?
