### ISSUE TITLE
Can't save contents

### ISSUE THREAD

**Issue by tomtomtomtony** [splitbrain/dokuwiki-stickbuilder#3]
I input the following text into DokuWiki ,but can't save or preview it:

<code bash [enable_line_numbers="true"]>
.
├── 0
│   ├── epsilon
│   ├── k
│   ├── nut
│   ├── nuTilda
│   ├── omega
│   ├── p
│   └── U
├── constant
│   ├── polyMesh
│   │   ├── boundary
│   │   ├── cellZones
│   │   ├── faces
│   │   ├── faceZones
│   │   ├── neighbour
│   │   ├── owner
│   │   ├── points
│   │   └── pointZones
│   ├── transportProperties
│   └── turbulenceProperties
├── obstacle.msh
└── system
    ├── blockMeshDict
    ├── controlDict
    ├── fvSchemes
    └── fvSolution
4 directories, 22 files
</code>
I have test lots of times. If the last six lines are delete, all will be ok, however, when the last six lines,(i.e from system to fvSolution) be added,I can't save or preview the contents. The page will be a blank page .

I use the 2018 Greebo edition of DokuWiki-portable in windows 10, offline.

To make things more clear, I have made a video.
https://send.firefox.com/download/0178ae51abd69842/#IbbKRx6uGgD1EjuXjJtRnQ.
I have tried similarity operation in Edge, and also can't save. So, I think, it may be not an error of web browsers.

**Comment by Klap-in** [comment]
See also: https://github.com/splitbrain/dokuwiki/issues/3015#issuecomment-600241292
